# Part 2. Vector and Matrix

In this lab, we will learn how to use Python to operate vectors and matrices. 

## 1. Example

### 1.1 Load data with pandas

In [48]:
import numpy as np
import pandas as pd

# load data with pandas
df = pd.read_csv('cars.csv')
# print(df)

# convert a pandas dataframe to a numpy array
X = df.values[:, 1:-1]
print(type(X))
print(X.shape)
print(X)

<class 'numpy.ndarray'>
(406, 7)
[[18.0 8 307.0 130 3504 12.0 70]
 [15.0 8 350.0 165 3693 11.5 70]
 [18.0 8 318.0 150 3436 11.0 70]
 [16.0 8 304.0 150 3433 12.0 70]
 [17.0 8 302.0 140 3449 10.5 70]
 [15.0 8 429.0 198 4341 10.0 70]
 [14.0 8 454.0 220 4354 9.0 70]
 [14.0 8 440.0 215 4312 8.5 70]
 [14.0 8 455.0 225 4425 10.0 70]
 [15.0 8 390.0 190 3850 8.5 70]
 [0.0 4 133.0 115 3090 17.5 70]
 [0.0 8 350.0 165 4142 11.5 70]
 [0.0 8 351.0 153 4034 11.0 70]
 [0.0 8 383.0 175 4166 10.5 70]
 [0.0 8 360.0 175 3850 11.0 70]
 [15.0 8 383.0 170 3563 10.0 70]
 [14.0 8 340.0 160 3609 8.0 70]
 [0.0 8 302.0 140 3353 8.0 70]
 [15.0 8 400.0 150 3761 9.5 70]
 [14.0 8 455.0 225 3086 10.0 70]
 [24.0 4 113.0 95 2372 15.0 70]
 [22.0 6 198.0 95 2833 15.5 70]
 [18.0 6 199.0 97 2774 15.5 70]
 [21.0 6 200.0 85 2587 16.0 70]
 [27.0 4 97.0 88 2130 14.5 70]
 [26.0 4 97.0 46 1835 20.5 70]
 [25.0 4 110.0 87 2672 17.5 70]
 [24.0 4 107.0 90 2430 14.5 70]
 [25.0 4 104.0 95 2375 17.5 70]
 [26.0 4 121.0 113 2234 12.5 70]


### 1.2 Operation for vector

In [49]:
#Get first row and the second to last row

x1 = X[0, :]
x2 = X[-2, :]

print(x1)
print(x2)

# Addition

y = x1 + x2
print(y)

[18.0 8 307.0 130 3504 12.0 70]
[28.0 4 120.0 79 2625 18.6 82]
[46.0 12 427.0 209 6129 30.6 152]


### 1.3 Operation for matrix

In [50]:
# Get first 5 rows and last 5 rows 

m1 = X[0:5, :]
m2 = X[-5:, :]

print(m1)
print(m2)

# Subtraction
m = m1 - m2
print(m)

[[18.0 8 307.0 130 3504 12.0 70]
 [15.0 8 350.0 165 3693 11.5 70]
 [18.0 8 318.0 150 3436 11.0 70]
 [16.0 8 304.0 150 3433 12.0 70]
 [17.0 8 302.0 140 3449 10.5 70]]
[[27.0 4 140.0 86 2790 15.6 82]
 [44.0 4 97.0 52 2130 24.6 82]
 [32.0 4 135.0 84 2295 11.6 82]
 [28.0 4 120.0 79 2625 18.6 82]
 [31.0 4 119.0 82 2720 19.4 82]]
[[-9.0 4 167.0 44 714 -3.5999999999999996 -12]
 [-29.0 4 253.0 113 1563 -13.100000000000001 -12]
 [-14.0 4 183.0 66 1141 -0.5999999999999996 -12]
 [-12.0 4 184.0 71 808 -6.600000000000001 -12]
 [-14.0 4 183.0 58 729 -8.899999999999999 -12]]


## 2 Task

### 2.1 Get the first column and the second to last column from X

In [51]:
# this is your code to get two vectors 
with open('output.txt', 'w') as f:
    v1 = X[:, 0]
    v2 = X[:, -2]

    print("First Column:\n", v1,file = f)
    print("Second to Last Column:\n", v2,file = f)

### 2.2 Perform following operations on these two vectors and print the result

In [52]:
with open('output.txt', 'a') as f:
    # 1. addition and subtraction
    print("Addition: {}\n".format(v1+v2),file = f)
    print("Subtraction: {}\n".format(v1-v2),file = f)

    # 2. element-wise multiplication
    print("Element-Wise Multiplication: {}\n".format(np.multiply(v1, v2)),file = f)

    # 3. inner product
    print("Inner Product: {}\n".format(np.inner(v1,v2)),file = f)

    # 4. three norms
    print("First Column Vector Norms:",file = f)
    print("\tL1-Norm: {}".format(np.linalg.norm(v1, ord = 1)),file = f)
    print("\tL2-Norm: {}".format(np.linalg.norm(v1, ord = 2)),file = f)
    print("\tInf-Norm: {}".format(np.linalg.norm(v1, ord=np.inf)),file = f)
    print("Second to Last Column Vector Norms:",file = f)
    print("\tL1-Norm: {}".format(np.linalg.norm(v2, ord = 1)),file = f)
    print("\tL2-Norm: {}".format(np.linalg.norm(v2, ord = 2)),file = f)
    print("\tInf-Norm: {}".format(np.linalg.norm(v2, ord=np.inf)),file = f)
    # 5. compute the distance between these two vectors
    print("Distance: {}".format(np.linalg.norm(v1 - v2, ord = 2)),file = f)

### 2.3 Get the first three columns and the last three columns from X

In [53]:
np.set_printoptions(threshold=np.inf)
with open('output.txt', 'a') as f:
    # this is your code to get two matrices: A, B
    A = X[:, 0:3]
    B = X[:, -3:]

    print("First Three Columns (Matrix A):\n", A,file = f)
    print("Last Three Columns (Matric B):\n",B,file = f)


### 2.4 Perform following operations on these two matrices and print the result

In [54]:
with open('output.txt', 'a') as f:
    # 1. addition and subtraction 
    print("Addition: {}\n".format(A+B),file = f)
    print("Subtraction: {}\n".format(A-B),file = f)

    # 2. compute the transpose of the second matrix: C = B^T, and print the shape of C
    C = np.transpose(B)
    print("Second Vector Transpose: {}\n".format(C),file = f)

    # 3. compute the product between A and C, and print the result and its shape
    AC = np.dot(A,C)
    print("A*C = {}\n".format(AC),file = f)

    # 4. compute the transpose of the first matrix: D = A^T, and print the shape of D
    D = np.transpose(A)
    print("First Vector Transpose: {}\n".format(D),file = f)

    # 5. compute the product between D and B, and print the result and its shape
    BD = np.dot(B,D)
    print("B*D = {}\n".format(BD),file = f)